{% set name = "prospect" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prospect-{{ version }}.tar.gz
  sha256: 62f28c83a852ee01779cfdbfb3063f069a179f01fce72f6517093c956abe66e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geopandas
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - scipy

test:
  imports:
    - prospect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://deppen8.github.io/prospect/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: prospect is a Python package to build and run simulations of archaeological surveys. It is designed to be a flexible tool that can be run with some sensible defaults or highly customized, depending on the user’s needs.
  dev_url: https://github.com/deppen8/prospect

extra:
  recipe-maintainers:
    - deppen8
